version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/neo-utils-go
    docker:
      - image: golang:1.8.3
        environment:
          GOPATH: /go
      - image: neo4j:3.2.7-enterprise
        environment:
          NEO4J_URL: http://neo4j:foobar@localhost:7474/db/data/
    steps:
      - checkout
      - run:
          name: Go get
          command: go get -t -d -v ./...
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Pre Tests
          command: '/usr/bin/curl -u neo4j:neo4j -H "Content-Type: application/json" -X POST -d ''{"password":"foobar"}''  http://localhost:7474/user/neo4j/password'
      - run:
          name: Run Tests
          command: |
            go test -race -v ./... 
workflows:
  version: 2
  test-project:
    jobs:
      - build
